
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import "./global.css";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <Navbar></Navbar>
        {children}</body>
      <Footer></Footer>
    </html>
  )
}
